site_name: aleksandr-makarov-dev.github.io
repo_url: https://github.com/aleksandr-makarov-dev/aleksandr-makarov-dev.github.io
repo_name: aleksandr-makarov-dev/aleksandr-makarov-dev.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    logo: material/code-array
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.top
    - navigation.sections
    - content.action.edit
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
  - git-revision-date-localized:
      enable_creation_date: true
